{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPtg0yqHtYYaTANJGdN0pML",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Samiksha2-cloud/Trendpulse-samiksha-yadav/blob/main/task-2%20data%20collection.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import json\n",
        "import requests\n",
        "import time\n",
        "from datetime import datetime\n",
        "\n",
        "# --- 1. Configuration & Constants ---\n",
        "BASE_URL = \"https://hacker-news.firebaseio.com/v0\"\n",
        "HEADERS = {\"User-Agent\": \"TrendPulse/1.0\"}\n",
        "DATA_FOLDER = \"data\"\n",
        "STORY_LIMIT_PER_CATEGORY = 25\n",
        "TOTAL_STORIES_TO_SCAN = 500\n",
        "\n",
        "# Fixed: Added commas and ensured proper dictionary structure\n",
        "CAT = {\n",
        "    \"technology\": [\"AI\", \"software\", \"tech\", \"code\", \"computer\", \"data\", \"cloud\", \"API\", \"GPU\", \"LLM\"],\n",
        "    \"worldnews\": [\"war\", \"government\", \"country\", \"president\", \"election\", \"climate\", \"attack\", \"global\"],\n",
        "    \"sports\": [\"NFL\", \"NBA\", \"FIFA\", \"sport\", \"game\", \"team\", \"player\", \"league\", \"championship\"],\n",
        "    \"science\": [\"science\", \"research\", \"study\", \"space\", \"physics\", \"biology\", \"discovery\", \"NASA\", \"genome\"],\n",
        "    \"entertainment\": [\"movie\", \"film\", \"music\", \"Netflix\", \"game\", \"book\", \"show\", \"award\", \"streaming\"]\n",
        "}\n",
        "\n",
        "def get_category(title):\n",
        "    \"\"\"Assigns a category based on keywords found in the title (case-insensitive).\"\"\"\n",
        "    title_lower = title.lower()\n",
        "    for category, keywords in CAT.items():\n",
        "        for keyword in keywords:\n",
        "            if keyword.lower() in title_lower:\n",
        "                return category\n",
        "    return None\n",
        "\n",
        "def fetch_data():\n",
        "    \"\"\"Main execution function to fetch, process, and save story data.\"\"\"\n",
        "\n",
        "    # Create the directory if it doesn't exist\n",
        "    if not os.path.exists(DATA_FOLDER):\n",
        "        os.makedirs(DATA_FOLDER)\n",
        "        print(f\"Created directory: {DATA_FOLDER}\")\n",
        "\n",
        "    # 2. Fetch the top story IDs\n",
        "    try:\n",
        "        print(\"Fetching top story IDs...\")\n",
        "        response = requests.get(f\"{BASE_URL}/topstories.json\", headers=HEADERS)\n",
        "        response.raise_for_status()\n",
        "        story_ids = response.json()[:TOTAL_STORIES_TO_SCAN]\n",
        "    except Exception as e:\n",
        "        print(f\"Failed to fetch top stories: {e}\")\n",
        "        return\n",
        "\n",
        "    collected_data = []\n",
        "    # Tracking counts to respect the 25-per-category limit\n",
        "    counts = {cat: 0 for cat in CAT.keys()}\n",
        "\n",
        "    print(\"Processing stories... this may take a moment.\")\n",
        "\n",
        "    # 3. Fetch individual story details\n",
        "    for story_id in story_ids:\n",
        "        # Stop if we have filled all categories (Optimization)\n",
        "        if all(count >= STORY_LIMIT_PER_CATEGORY for count in counts.values()):\n",
        "            print(\"Reached the limit for all categories.\")\n",
        "            break\n",
        "\n",
        "        try:\n",
        "            item_url = f\"{BASE_URL}/item/{story_id}.json\"\n",
        "            item_res = requests.get(item_url, headers=HEADERS)\n",
        "            item_res.raise_for_status()\n",
        "            story = item_res.json()\n",
        "\n",
        "            # Skip if it's not a story or has no title\n",
        "            if not story or 'title' not in story:\n",
        "                continue\n",
        "\n",
        "            category = get_category(story['title'])\n",
        "\n",
        "            # If it matches a category and we still need more for that category\n",
        "            if category and counts[category] < STORY_LIMIT_PER_CATEGORY:\n",
        "                story_entry = {\n",
        "                    \"post_id\": story.get(\"id\"),\n",
        "                    \"title\": story.get(\"title\"),\n",
        "                    \"category\": category,\n",
        "                    \"score\": story.get(\"score\", 0),\n",
        "                    \"num_comments\": story.get(\"descendants\", 0),\n",
        "                    \"author\": story.get(\"by\"),\n",
        "                    \"collected_at\": datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
        "                }\n",
        "\n",
        "                collected_data.append(story_entry)\n",
        "                counts[category] += 1\n",
        "\n",
        "                # Check if we JUST hit the limit for this specific category\n",
        "                if counts[category] == STORY_LIMIT_PER_CATEGORY:\n",
        "                    print(f\"Finished collecting for: {category}. Cooling down for 2 seconds...\")\n",
        "                    time.sleep(2)\n",
        "\n",
        "        except Exception as e:\n",
        "            print(f\"Error fetching item {story_id}: {e}\")\n",
        "            continue\n",
        "\n",
        "    # 4. Save to JSON file\n",
        "    date_str = datetime.now().strftime(\"%Y%m%d\")\n",
        "    filename = f\"{DATA_FOLDER}/trends_{date_str}.json\"\n",
        "\n",
        "    with open(filename, \"w\") as f:\n",
        "        json.dump(collected_data, f, indent=4)\n",
        "\n",
        "    print(f\"--- SUCCESS ---\")\n",
        "    print(f\"Collected {len(collected_data)} stories total.\")\n",
        "    print(f\"Saved to {filename}\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    fetch_data()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "eUlYADXpxlVj",
        "outputId": "91f152d1-31e3-426b-85a1-6a30d7ee2f10"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Fetching top story IDs...\n",
            "Processing stories... this may take a moment.\n",
            "Finished collecting for: technology. Cooling down for 2 seconds...\n",
            "Finished collecting for: entertainment. Cooling down for 2 seconds...\n",
            "--- SUCCESS ---\n",
            "Collected 78 stories total.\n",
            "Saved to data/trends_20260405.json\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import glob\n",
        "import pandas as pd\n",
        "def load_latest_json():\n",
        "    # This finds the most recent json file in your data folder\n",
        "    list_of_files = glob.glob('data/trends_*.json')\n",
        "    if not list_of_files:\n",
        "        print(\"No JSON files found in data/ folder!\")\n",
        "        return None\n",
        "\n",
        "    latest_file = max(list_of_files, key=os.path.getctime)\n",
        "    df = pd.read_json(latest_file)\n",
        "    print(f\"Loaded {len(df)} stories from {latest_file}\")\n",
        "    return df\n",
        "\n",
        "def clean_data(df):\n",
        "    if df is None: return\n",
        "\n",
        "    # 2. Clean the Data\n",
        "\n",
        "    # Remove Duplicates: ensures post_id is unique\n",
        "    initial_count = len(df)\n",
        "    df = df.drop_duplicates(subset=['post_id'])\n",
        "    print(f\"After removing duplicates: {len(df)}\")\n",
        "\n",
        "    # Missing values: remove rows where critical info is null\n",
        "    df = df.dropna(subset=['post_id', 'title', 'score'])\n",
        "    print(f\"After removing nulls: {len(df)}\")\n",
        "\n",
        "    # Data types: convert score and comments to integers\n",
        "    # 'coerce' handles any weird text by turning it into a NaN (which we then fill with 0)\n",
        "    df['score'] = pd.to_numeric(df['score'], errors='coerce').fillna(0).astype(int)\n",
        "    df['num_comments'] = pd.to_numeric(df['num_comments'], errors='coerce').fillna(0).astype(int)\n",
        "\n",
        "    # Low quality: Keep only stories with a score of 5 or higher\n",
        "    df = df[df['score'] >= 5]\n",
        "    print(f\"After removing low scores: {len(df)}\")\n",
        "\n",
        "    return df\n",
        "\n",
        "def save_and_summarize(df):\n",
        "    if df is None: return\n",
        "\n",
        "    # 3. Save as CSV\n",
        "    output_path = 'data/trends_clean.csv'\n",
        "    df.to_csv(output_path, index=False)\n",
        "    print(f\"\\nSaved {len(df)} rows to {output_path}\")\n",
        "\n",
        "    # Print a quick summary: how many stories per category\n",
        "    print(\"\\nStories per category:\")\n",
        "    print(df['category'].value_counts())\n",
        "\n",
        "# --- Execution ---\n",
        "if __name__ == \"__main__\":\n",
        "    raw_df = load_latest_json()\n",
        "    clean_df = clean_data(raw_df)\n",
        "    save_and_summarize(clean_df)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "hQ765WAE2PZn",
        "outputId": "9e0f0295-e01a-4b07-e5ad-2cf383005363"
      },
      "execution_count": 27,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Loaded 78 stories from data/trends_20260405.json\n",
            "After removing duplicates: 78\n",
            "After removing nulls: 78\n",
            "After removing low scores: 75\n",
            "\n",
            "Saved 75 rows to data/trends_clean.csv\n",
            "\n",
            "Stories per category:\n",
            "category\n",
            "technology       24\n",
            "entertainment    23\n",
            "science          12\n",
            "worldnews        10\n",
            "sports            6\n",
            "Name: count, dtype: int64\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "ugz68CyPDL_r"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}